# Generated by Django 5.2.2 on 2025-08-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity_sold',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='selling_price',
        ),
    ]
